name: ams_count
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  uuid: ^3.0.7
  formz: ^0.6.0
  dio: ^5.1.2
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  connectivity_plus: ^4.0.2
  permission_handler: ^10.2.0
  get: ^4.6.5
  validators: ^3.0.0

  ## Local DB
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.0
  path: ^1.8.3

  ## UI
  #shimmer: ^2.0.0
  font_awesome_flutter: ^10.4.0
  animations: ^2.0.7
  #  animated_text_kit: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.3.2
  bot_toast: ^4.0.3
  # flutter_svg : ^0.17.4
  #  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  msh_checkbox: ^2.0.1
  pluto_grid: ^7.0.2
  auto_size_text: ^3.0.0
  fl_chart: ^0.63.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^22.2.9
  syncfusion_flutter_gauges: ^22.2.9
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  dropdown_button2: ^2.3.8
  simple_barcode_scanner: ^0.0.8
  easy_search_bar: ^2.5.0
  image_picker: ^1.0.2
  rflutter_alert: ^2.0.7
  photo_view: ^0.14.0
  flutter_image_preview: ^0.1.1
  sqflite: ^2.3.0
  change_app_package_name: ^1.1.0
  flutter_swiper_plus: ^2.0.4
  flutter_onboarding_slider: ^1.0.10
  flutter_slidable: ^3.0.0
  iconforest_iconic: ^1.0.0+1
  anim_search_bar: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.10.0"

  ## Local DB
  drift_dev: ^2.8.2
  build_runner: ^2.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  #  android: true
  #  ios: true
  #  remove_alpha_ios: true
  #  adaptive_icon_padding: false
  #  adaptive_icon_foreground: "assets/images/wms_icons.jpg"
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/capacitor-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie_files/
    - assets/fonts/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: Noto-Thai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Medium.ttf
        - asset: assets/fonts/NotoSansThai-Light.ttf
        - asset: assets/fonts/NotoSansThai-Bold.ttf
